# Outputting
permalink: /:categories/:title.html

# Conversion
markdown:         kramdown
highlighter:      rouge
excerpt_separator: <!--more-->

   url: kurdishblark.github.io
   baseurl: /KurdishLyricsCorpus